### ISSUE TITLE
Add feed?

### ISSUE THREAD

**Issue by librarianmage** [iagoleal/iagoleal.github.io#1]
Hello! I really enjoy the posts you've made. Would you consider adding an RSS/Atom feed to the site?

**Comment by iagoleal** [comment]
Sure! To be honest, I have been thinking about adding it for some time, but I kept postponing because I didn't knew someone actually reads it.
I will add the feed as soon as I get some free time (perhaps this weekend?) :)

**Comment by iagoleal** [comment]
Just added a RSS feed!
You can access it at https://iagoleal.com/rss.xml

Later I may also add an Atom feed since they seem similar enough to generate
